./install-owns.sh
./install-upgrade.sh
./install-packages.sh
./install-emerald.sh
./install-skype.sh
./install-pbzip-pigz-default.sh
./install-zsh-default.sh
./install-git-color.sh
./install-eclipse-kepler.sh
./install-configs.sh
./install-apparmor-enforce.sh
./remove-unnecessary-packages.sh
