[Desktop Entry]
Name=v
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Clearlooks
MetacityTheme=Spidey
IconTheme=menta
GtkColorScheme=fg_color:#ffffffffffff,bg_color:#3b3b3b3b3e3e,text_color:#ffffffffffff,base_color:#3b3b3b3b3e3e,selected_fg_color:#ffffffffffff,selected_bg_color:#733300000000,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#3b3b3b3b3e3e
CursorTheme=DMZ-Black
CursorSize=18
BackgroundImage=/usr/share/backgrounds/mate/nature/RainDrops.jpg
